import os.path
print("Welcome to Pistributed Server Setup.")
print("Do not run on unsecure or slow servers. Do not run on servers you don't own or have control over*. You may get lots of requests to your server. This depends if lots of people are using your Pistributed server.")
print("*having control over requires permission if there is a server owner that isn't yourself.")
print("""This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.""")
print("By continuing, you agree to these terms, disclaimers, and acknowledge that there is NO WARRANTY.")
print("Security is not guarenteed. I am not responsible for ANY damages or attempts of damages to ANY computer, phone, or device running Pistributed's client or server.")
input("I agree, and would like to continue. (to continue, press enter)")
email = input("What email would you like to display for server support? THIS WILL BE MADE PUBLIC ")
called = input("What would you like to be called? (ex: Wish) THIS WILL BE MADE PUBLIC ")
print("Thank you! Creating a .env file... Make sure to run server.py when you are ready!")
with open(".env", "w") as file:
    file.write("EMAIL=" + email + "\nNAME=" + called)
isExist = os.path.exists("picalc")
if not isExist:
   os.makedirs("picalc")
   print("Picalc not found, creating")
with open("picalc/pi.txt", "w") as pifile:
    pifile.write("No clients have connected yet. Become one of the first!")
    print("Created picalc/pi.txt successfully. Do NOT edit this file!")
with open("ver.txt", "w") as versionfile:
    versionfile.write("1.4")
    print("Created version file. Server will not work without this!!!")